### Create a new Movie
POST {{base_endpoint}}/movie
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Inception",
  "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
  "genre": "Science Fiction",
  "releaseDate": "2010-07-16",
  "isPrivate": true
}

### Create a new Movie
POST {{base_endpoint}}/movie
Content-Type: application/json
Authorization: {{token}}

{
  "title": "The Shawshank Redemption",
  "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
  "genre": "Drama",
  "releaseDate": "1994-09-23",
  "isPrivate": false
}

### Get movies
GET {{base_endpoint}}/movies
Content-Type: application/json
Authorization: {{token}}

### Register new user
POST {{base_endpoint}}/user/register
Content-Type: application/json

{
  "name": "Christian",
  "lastname": "Martinez",
  "email": "chris@gmail.com",
  "phone": "3736363",
  "password": "Password!NewOne"
}

### Login user
POST {{base_endpoint}}/user/login
Content-Type: application/json

{
  "email": "chris@gmail.com",
  "password": "Password!NewOne"
}

### Login user
POST {{base_endpoint}}/user/login
Content-Type: application/json

{
  "email": "doe2@gmail.com",
  "password": "Password!NewOne"
}