version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_movies_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiftysevenblocks
      MYSQL_USER: cristian
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: