version: '3.8'

services:
  backend:
    container_name: backend-movies-57blocks
    image: backend-movies-57blocks-springboot:latest
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fiftysevenblocks
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  mysql:
    image: mysql:8.0
    container_name: mysql_movies_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiftysevenblocks
      MYSQL_USER: cristian
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: